### ISSUE TITLE
It is not clear how to run this Scritpt for noobs...

### ISSUE THREAD

**Issue by jjjkkklll** [akameco/extract-react-intl-messages#13]
Hi,

I do not understand how to run this script, yes I am a noob... but

Run Script
`$ extract-messages -l=en,ja -o app/translations -d en --flat false 'app/**/!(*.test).js'`

is not really helpfull... Do I need to run this command in the shell where I ran the npm install...?
-this is what I get:

`
$ extract-messages -l=en,ja -o app/translations -d en --flat false 'app/**/!(*.test).js'
bash: extract-messages: command not found
`

So I need to run it somewhere else, or do something else before running it?

Please explain what is the difference between the packages: extract-react-intl/extract-react-intl-messages

Thank you

**Comment by akameco** [comment]
Thank you for your feedback.
Try this command.

```sh
npm i -D extract-react-intl-messages
npm run extract-messages -l=en,ja -o app/translations -d en --flat false 'app/**/!(*.test).js'
```

`extract-react-intl` package is for API usage not cli.

**Comment by jjjkkklll** [comment]
Thank you for your fast respond. 

I am getting this error now:
```
npm info using npm@5.5.1
npm info using node@v8.9.0
npm ERR! missing script: extract-messages
```

The package is installed for sure. Maybe there is something wrong with the directories?

**Comment by jjjkkklll** [comment]
I have created a new create-react-app.

App.js
```

import React, {Component} from 'react';
import './App.css';

import {IntlProvider, FormattedMessage} from 'react-intl';

const message = {
    en: {
        "hello": "hello"
    },
    sp: {
        "hello": "hola"
    }
}


class App extends Component {
    constructor(){
        super()

       this.state= {lang:'en'}

    }



    render() {
        return (
            <IntlProvider locale="en" messages={message[this.state.lang]}>


                <div className="App">
                    <FormattedMessage
                        id='hello'
                        defaultMessage='Hello'
                    />

                    <button onClick={() => this.setState({
                        lang: 'en'
                    })}>

                        click to switch language to EN
                    </button>

                    <button onClick={() => this.setState({
                        lang: 'sp'
                    })}>

                        click to switch language to SP
                    </button>

                </div>

            </IntlProvider>

        );
    }
}

export default App;
```


package.json
```
`{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-intl": "^2.4.0",
    "react-scripts": "1.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "extract-react-intl-messages": "^0.8.1"
  }
}`
```

when I run:
`npm run extract-messages -l=en,ja -o app/translations -d en --flat false 'app/**/!(*.test).js'`

This error is trown:
````
npm info it worked if it ends with ok
npm info using npm@5.5.1
npm info using node@v8.9.0
npm ERR! missing script: extract-messages
```
`

Did this help?

**Comment by akameco** [comment]
OK, I understand.

First, this tool needs `.babelrc`.

.babelrc

```
{
  "presets": [
    "react-app"
  ]
}
```

Secound, update npm script like this.

```
{
  "name": "intl-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
	"intl": "NODE_ENV=development extract-messages -l=en,ja -o src/i18n -d en --flat false 'src/**/!(*.test).js'"
  },
  "devDependencies": {
    "extract-react-intl-messages": "^0.8.1"
  }
}
```

And, run.

```
npm run intl
```

Finish🎉

**Comment by jjjkkklll** [comment]
Thanks, it worked for the create-react-app, but my understanding is still very limited and therefore it does not work when I try to transfer this to my other app. Which is a meteor app btw. :/

If I use the .babelrc preset, I get:

`Couldn't find preset "react-app" relative to directory `

so it has to be something different than ` react-app`?

If I use it without the preset, it starts to check all the files, but throws an error:

```
SyntaxError: imports/foo.js: Unexpected token (40:15)
  38 | 
  39 |     render() {
> 40 |         return <div>test</div>
     |                ^
  41 |     }
  42 | }

```

**Comment by akameco** [comment]
If you already have .babelrc, don't need anything.This tool is using babelrc for parsing code. If you use jsx, you should add babel-preset-react. if you use flowtype, you should add babel-preset-flow...etc etc...
