### ISSUE TITLE
Error: File not found :(

### ISSUE THREAD

**Issue by sidati** [akameco/extract-react-intl-messages#15]
Hi, thanks for the effort 👍 

- version: ^0.8.2
- `node` version: v8.9.4
- `npm` (or `yarn`) version: 1.5.1 (Yarn)

**Do you want to request a *feature* or report a *bug*?:**
**Bug**

**What is the current behavior?:**
Throw Error (Error: File not found ('src/components/app.jsx')
command : `extract-messages -l=ar -o src/locales 'src/components/app.jsx'`
the file is there, trying `extract-messages -l=ar -o src/locales 'src/**/*.jsx'` throws `File not found ('src/**/*.jsx')` same thing for JS files

**What is the expected behavior?:**
Extract messages

**Suggested solution:**
I have no idea

P.S. **Im using create-react-app**

**Comment by akameco** [comment]
If you are using the `env` property with `.babelrc`, please use `NODE_ENV = development`.
