### ISSUE TITLE
Crashes for empty directory

### ISSUE THREAD

**Issue by maciej-gurban** [akameco/extract-react-intl-messages#17]
- version:
- `node` v8.7.0:
- `npm` 5.4.2:

Do you want to request a *feature* or report a *bug*?:
**Bug**

**What is the current behavior?:**
When trying to parse multiple directories, if one of them is empty the script crashes with `Error: File not found (./path/to/empty/directory/**/!(*.test).js)`

**What is the expected behavior?:**
Script does not crash, and either creates an empty file for empty directory (since no strings were found), or gives a warning that nothing was found.

**Suggested solution:**
As above.

**Comment by akameco** [comment]
I think it is correct.
If no file matches, an error should occur.
