### ISSUE TITLE
TypeError: fn is not a function

### ISSUE THREAD

**Issue by datenreisender** [akameco/extract-react-intl-messages#21]
- version: 0.9.1
- `node` version: v8.11.2
- `npm` (or `yarn`) version: 5.6.0

**Do you want to request a *feature* or report a *bug*?:**

Bug

**What is the current behavior?:**

When invoking `extract-messages -o translations -l de src/**/*.js` the output is
```
TypeError: fn is not a function
    at list.map.x (/Users/ms/p/vaamo/vam-frontend/node_modules/extract-react-intl/index.js:25:42)
    at Array.map (<anonymous>)
    at /Users/ms/p/vaamo/vam-frontend/node_modules/extract-react-intl/index.js:25:8
    at extractFromFile (/Users/ms/p/vaamo/vam-frontend/node_modules/extract-react-intl/index.js:74:16)
    at Array.map (<anonymous>)
    at pify.then.files (/Users/ms/p/vaamo/vam-frontend/node_modules/extract-react-intl/index.js:93:32)
    at <anonymous>
``` 

and the file `translations/de.json` contains only `{}`.

**What is the expected behavior?:**

No error output and a correctly filled `translations/de.json`.

**Suggested solution:**

I am still trying to minimise the project this happens on but already wanted to open the issue in case somebody knows immediatly what might trigger the bug.

**Comment by akameco** [comment]
@datenreisender Could you show me reproduction repository?

**Comment by datenreisender** [comment]
Narrowing it down I discovered, that it was caused by the old version 6.21.0 of `babel-core` we still had in the dependencies. Upgrading to the latest 6.26.3 fixed the problem. So, this is no bug here in `extract-react-intl-messages` and I close this bug. Sorry for the hassle.
