### ISSUE TITLE
Not working with babel-plugin-react-intl-auto?

### ISSUE THREAD

**Issue by Victorien-Tardif** [akameco/extract-react-intl-messages#23]
- version: 0.10.0
- `node` version: 10.4.1
- `npm`  version: 6.2.0

Using `babel-plugin-react-intl-auto` 1.1.0, I always encounter an error: 
`[React Intl] Message Descriptors require an id and defaultMessage.`

How can I fix this?

**Comment by Victorien-Tardif** [comment]
It turns out that the problem only occurs when `defineMessages` is used inside a Component. 
I had something like
`
class MyComponent extends Component {
  getMessages() {
    return defineMessages({
      hello: 'Hello',
    });
  }
  render(){
    return (<p>{this.getMessages().hello}</p>)
  }
}
`
but when I move defineMessages out of it, like this:
`
const messages = defineMessages({
  hello: 'Hello',
});
class MyComponent extends Component {
  render(){
    return (<p>{messages.hello}</p>)
  }
}
`
it works!

**Comment by akameco** [comment]
@Victorien-Tardif Thanks for the report. `babel-plugin-react-intl-auto` only supports top level functions.
