### ISSUE TITLE
Produce flat json structure

### ISSUE THREAD

**Issue by Filson14** [akameco/extract-react-intl-messages#25]
- version: 0.10.0
- `node` version: 10.4.1
- `npm` (or `yarn`) version: 6.1.0

**Do you want to request a *feature* or report a *bug*?:**
Not sure :wink:

**What is the current behavior?:**
The extraction process is performed correctly. I use it to produce json files. The 'flat' flag is set to true by default, but the result is nested structure. Am I missing the real responsibility of that flag or it's not working well (if the latter, I report a bug).

**What is the expected behavior?:**
React-Intl's IntlProvider expects single level object in messages props, so it is needed functionality to generate one. I know it is possible to set up additional step to the script and flatten those files, but if extract-react-intl-messages can (or already should) do it automatically, why not to use it?

**Comment by akameco** [comment]
@Filson14 Hmm, show me reproduction repository

**Comment by Filson14** [comment]
Hello @akameco. Thanks for your response.
During preparation of the reproduction repo I found some failures in my npm scripts... Long story short - the flat flag was always overwritten with **false**. After fix, it work as expected.
Thanks for your help (classic duck-debugging :wink:).

Nice tool, by the way :+1:

**Comment by mlenser** [comment]
@akameco this is a great tool, thank you so much!

Perhaps there is an issue in the documentation around `flat` though. The `format` defaults to json and `flat` defaults to true if json. So if no format is provided I'd expect flat to be the default, but that isn't the case. Specifying `--flat true` fixes it. Maybe something to clean up?

Thanks again for this great tool!
