### ISSUE TITLE
Extracting messages with defineMessages exported from custom module does not work.

### ISSUE THREAD

**Issue by Filson14** [akameco/extract-react-intl-messages#27]
- version: 0.10.0
- `node` version: 10.4.1
- `npm` version: 6.1.0

**Do you want to request a *feature* or report a *bug*?:**
Bug or support

**What is the current behavior?:**
In my project I managed JS module to handle internationalization. It is based on react-intl but extends it with some custom components, predefined configs, extra features etc.
Because of that, I wanted to avoid necessity of imports from react-intl AND my own module, so decided to export required react-intl elements via my modules' index.js file.

Everything works great, but I figured out that when I run npm script to extract messages with extract-react-intl-messages, it does not work any more. It creates files, but there are no messages. Something like on screenshots below.

![image](https://user-images.githubusercontent.com/4540538/49757343-7b733880-fcbc-11e8-9ebf-2370285f8ba2.png)

![image](https://user-images.githubusercontent.com/4540538/49757467-ca20d280-fcbc-11e8-9c83-6304e6046bbb.png)

If I import _defineMessages_ directly from **react-intl** it works as expected.

**What is the expected behavior?:**
I expect it to work exactly the same with both variants. Not sure why it's not working correctly. _defineMessages_ is not any special kind of function. In fact, it does nothing except returning passed values.

**Comment by Filson14** [comment]
@akameco , can You take a look?

**Comment by akameco** [comment]
Sorry. can not cope. Since we are using babel-plugin-react-intl we need to import from react-intl. https://github.com/yahoo/babel-plugin-react-intl

**Comment by Filson14** [comment]
OK, so I gotta check there. Thanks.
