### ISSUE TITLE
Translating placeholder texts 

### ISSUE THREAD

**Issue by xBootstrap** [akameco/extract-react-intl-messages#28]
Hi,

Thank you for of all, is there a way to to translate placeholders texts in the form please ?

**Comment by xBootstrap** [comment]
Hi,

I was able to achieve that by doing following

<pre>
<IntlMsg id="id.for-translation">
            {YourPlaceHoldTexts => <Input type="text" name="city" placeholder={YourPlaceHoldTexts } />}
          </IntlMsg>
</pre>

**Comment by akameco** [comment]
This is not an Issue of this repository.
