### ISSUE TITLE
Pluging doesn't extract all values to json

### ISSUE THREAD

**Issue by Tomekmularczyk** [akameco/extract-react-intl-messages#3]
I have prepared a repo to demonstrate the problem:

https://github.com/Tomekmularczyk/react-starter/tree/intl

`yarn intl` creates json files in `/static/intl/` directory but they are missing lot of messages declared with defineMessages across `src` directory.

**Comment by akameco** [comment]
Because it will overwrite if the key already exists.

`extract-messages -l=en,pl -o ./static/intl -d en --flat 'src/**/!(*.test).jsx'`

```diff
{
  "src.pages.dashboard.headerTitle": "Message to greet the user.",
  "src.pages.dashboard.fourOfour": "go to 404 page",
  "src.pages.dashboard.profile": "go to profile",
  "src.pages.dashboard.profile.headerTitle": "Hello in profile!",
  "src.pages.headerTitle": "No match for {path}",
  "src.pages.dashboard": "Dashboard"
}
```

`extract-messages -l=en,pl -o ./static/intl -d en --flat false 'src/**/!(*.test).jsx'`

```diff
{
  src: {
    pages: {
      dashboard: 'Dashboard',
      headerTitle: 'No match for {path}'
    }
  }
}
```

In this case we can not determine if `dashboard` is `string` or `object`.
I recommend changing the name of the key, using the `flat` option, or moving to the directory.

**Comment by akameco** [comment]
I updated `babel-plugin-react-intl-auto` .
Added `filebase` option.

ref https://github.com/akameco/babel-plugin-react-intl-auto/pull/4

ex:

.babelrc
```
{
  "plugins": [ ["react-intl-auto", { "filebase": true }] ]
}
```

```sh
$ rm static/intl/en.json
$ npm run intl
```

en.json

```json
{
  "src": {
    "pages": {
      "Page404": {
        "headerTitle": "No match for {path}"
      },
      "dashboard": {
        "index": {
          "fourOfour": "go to 404 page",
          "headerTitle": "Message to greet the user.",
          "profile": "go to profile"
        },
        "profile": {
          "index": {
            "headerTitle": "Hello in profile!"
          }
        }
      },
      "index": {
        "dashboard": "Dashboard",
        "headerTitle": "Welcome to React"
      }
    }
  }
}
```
