### ISSUE TITLE
[Support] Is it not compatible with babel v6 any more?

### ISSUE THREAD

**Issue by Filson14** [akameco/extract-react-intl-messages#32]
Is this tool incompatible with babel6 because of changes introduced in 0.12 version?
When I was testing _module-name_ feature on my branch everything worked fine. Now, I found that extracting messages to files is not possible :disappointed:

- version: 0.13
![image](https://user-images.githubusercontent.com/4540538/52411928-9a842000-2add-11e9-86e7-cf76c051af0a.png)

**Comment by Filson14** [comment]
I forgot to say that currently I use babel 6.26.0 but even when applied _babel-upgrade_ it doesn't work (with newer version nothing works as it should :yum:, while error mentioned above occures only when extracting messages).

@akameco, I would really appreciate Your help. 5!

**Comment by Filson14** [comment]
So now it really needs Babel7 to work?! I would consider it a major change :wink:

**Comment by akameco** [comment]
Published :)

Try:

```
npm install --save-dev extract-react-intl-messages0.14.0
```

**Comment by Filson14** [comment]
Awesome! :fireworks: It looks like it works as a charm.
Thank You for your help :hand:
