### ISSUE TITLE
Support variable

### ISSUE THREAD

**Issue by Victorien-Tardif** [akameco/extract-react-intl-messages#33]
- version: 0.14.0
- `node` version: 11.9.0
- `yarn` version: 1.13.0

**report a *bug***

The script is not working using variables:
```
const messages = { hello: 'hello world' }

export default defineMessages(messages)
```
**What is the current behavior?:**

[React Intl] `defineMessages()` must be called with an object expression with values that are React Intl Message Descriptors, also defined as object expressions.

**Comment by akameco** [comment]
This is not a problem with this library. Check https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl
