### ISSUE TITLE
.js was unexpected at this time

### ISSUE THREAD

**Issue by IskanderMustafin** [akameco/extract-react-intl-messages#34]
- version: 0.14/1.0.0 (explicitly tried both version, I guess they are same)
- Windows 10
- Babel 7
- `node` version: 10.13
- `npm` (or `yarn`) version: YARN 1.13/ NPM 6.41 (tried both)
**Do you want to request a *feature* or report a *bug*?:**
Bug
**What is the current behavior?:**
I'm getting error when running this command: 

```

"scripts": {
        "extract-messages": "extract-messages -l=en,ja -o ./translations -d en --flat false 'app/**/!(*.test).js'"
    },
```
Error message: `.js was unexpected at this time`

**What is the expected behavior?:**

Should run without errors and produce localization files

**Suggested solution:**

**Comment by henus** [comment]
On Windows when using quotes in scripts you need to use double quotes due to how Windows handles them on the command line (in package.json must be escaped double quotes).
```
"scripts": {
        "extract-messages": "extract-messages -l=en,ja -o ./translations -d en --flat false \"app/**/!(*.test).js\""
    },
```

**Comment by IskanderMustafin** [comment]
@henus  thanks, it worked out
