### ISSUE TITLE
Does not work with Typescript?

### ISSUE THREAD

**Issue by slorber** [akameco/extract-react-intl-messages#35]
Hi,

I understand this can be quite challenging to support but that would be useful to be able to use this on typescript projects. In my case it's a Gatsby site with Typescript plugin, so there's not even a .babelrc config. Not sure how this can be done, just reporting that this script is failing on such a file:

```

import React, { ReactNode } from 'react';
import classnames from 'classnames';

const CartItem = ({
  label,
  price,
  children,
}: {
  label: string;
  price: number;
  children: ReactNode;
}) => (
  <article className="cart-item">
    <p className="cart-item__title">
      <b>{label}</b>
      <span className="cart-item__price">{price}€</span>
    </p>
    <p className="cart-item__detail">{children}</p>
  </article>
);

export default CartItem;

```

**Comment by LucienLee** [comment]
you can install `@babel/preset-typescript` and add to `.babelrc` to work with typescript

**Comment by Evanion** [comment]
```
extract-messages -l=en,sv -o src/Locales -d en --flat false 'src/**/!(*.test).ts'
```
I just ran this on my React-native project that uses TypeScript, and it extracted the messages just fine. I'm confused what your issue is. What is the error you are getting? 
The code you included doesn't contain any react-intl code, The label is passed in as a prop from the parent component.

**Comment by akameco** [comment]
babel is required.
https://babeljs.io/docs/en/babel-preset-typescript

```
yarn add --dev @babel/core @babel/cli @babel/preset-typescript
```

.babelrc

```json
{
  "presets": ["@babel/preset-typescript"]
}
```
