### ISSUE TITLE
Empty default string [React Intl] Message Descriptors require an `id` and `defaultMessage`

### ISSUE THREAD

**Issue by Yuripetusko** [akameco/extract-react-intl-messages#36]
- version: 1.0.1
- `node` version: 10.1
- `npm` (or `yarn`) version: 1.15.2

**Do you want to request a *feature* or report a *bug*?:*Bug* 

**What is the current behavior?:**

```
export default defineMessages({
  toolsTitle: '',
});
```

```
const extractReactIntlMessages = require('extract-react-intl-messages');

const locales = ['en', 'en-GB'];
const pattern = 'components/**/*.ts';
const buildDir = 'static/i18n/locales';
const defaultLocale = 'en';

extractReactIntlMessages(locales, pattern, buildDir, { defaultLocale }).then(
  () => {
    console.log('finish');
  },
);
```

`[React Intl] Message Descriptors require an `id` and `defaultMessage``
**What is the expected behavior?:**

**Suggested solution:**
Should allow default empty strings?

**Comment by akameco** [comment]
Use with [babel-plugin-react-intl-auto](https://github.com/akameco/babel-plugin-react-intl-auto).
