### ISSUE TITLE
Whitespace at end of strings is stripped

### ISSUE THREAD

**Issue by EmpireJones** [akameco/extract-react-intl-messages#37]
extract-react-intl-messages - 0.8.2

**Do you want to request a *feature* or report a *bug*?:**
bug

**What is the current behavior?:**
Whitespace at the end of a string is removed

**What is the expected behavior?:**
Extracted text should match the input text

**Suggested solution:**
Don't strip whitespace

**Comment by akameco** [comment]
This is not a problem with this library. Check https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl

**Comment by EmpireJones** [comment]
This change has been integrated into babel-plugin-react-intl @ 4.1.13
https://github.com/formatjs/formatjs/releases/tag/babel-plugin-react-intl%404.1.13.

Could babel-plugin-react-intl be updated in this project to integrate that change?

**Comment by akameco** [comment]
@EmpireJones Released v2.3.0 🚀 https://github.com/akameco/extract-react-intl-messages/releases/tag/v2.3.0

**Comment by EmpireJones** [comment]
@akameco Awesome, thank you!!
