### ISSUE TITLE
Support for extracting message and IDs from intl.formatMessage function

### ISSUE THREAD

**Issue by tmkasun** [akameco/extract-react-intl-messages#38]
- version: 1.0.1
- `node` version: v10.16.0
- `npm` (or `yarn`) version: 6.9.0

**Do you want to request a *feature* or report a *bug*?: 

Feature

**What is the current behavior?: 

Do not support extracting message text and ID from `intl.formatMessage` function call

**What is the expected behavior?: 

When extracting messages and IDs , Extract them from `intl.formatMessage` function calls as well

**Suggested solution: 

Accept the  `extractFromFormatMessageCall` argument in [`extract-messages`](https://github.com/akameco/extract-react-intl-messages/blob/master/cli.js#L72) command and pass it to [`babel-plugin-react-intl`](https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl) through [extract-react-intl](https://github.com/akameco/extract-react-intl/blob/master/index.js#L72)

So that, When `extractFromFormatMessageCall` is passed as an argument, It will generate the message text and IDs passed to `intl.formatMessage` calls.

> extractFromFormatMessageCall: Opt-in to extract from intl.formatMessage call with the same restrictions, e.g: has to be called with object literal such as intl.formatMessage({ id: 'foo', defaultMessage: 'bar', description: 'baz'})

**Comment by tmkasun** [comment]
Hi All,

I have sent these two PRs as a possible implementation for this feature request. Please review

- https://github.com/akameco/extract-react-intl-messages/pull/39
- https://github.com/akameco/extract-react-intl/pull/21

**Comment by akameco** [comment]
resolved #42 . Released in v1.1.0
