### ISSUE TITLE
What to do with locale files

### ISSUE THREAD

**Issue by apuntovanini** [akameco/extract-react-intl-messages#41]
Not an issue, just a question: when exporting locale files, and using extract-messages with react-intl-auto I end up with a plain object with ids and empty strings.
How do you suggest one should go on from this? 
The way I thought I could work on locale was to obtain an `it.json` file, for instance, with english translations, and translate line by line just editing the file. However the ID is not clear enough, and I have to go back and forth from then `en.json` file to check what I should translate..I'm surely doing something wrong in the process...any suggestions?
Thanks!
Andrea

**Comment by akameco** [comment]
Not wrong. However, it is easier to proceed by copying `en.json` to `lt.json` first and then proceeding.
