### ISSUE TITLE
Doesn't work with babel.config - only looks for .babelrc

### ISSUE THREAD

**Issue by apuntovanini** [akameco/extract-react-intl-messages#48]
- version: 2.2.1
- `node` version: 12.40
- `npm` (or `yarn`) version: yarn 1.17.3

**Do you want to request a *feature* or report a *bug*?:**
 A bug

**What is the current behavior?:**
In a monorepo structure tried to run extract-messages in a package folder, raises `Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation`

**What is the expected behavior?:**
That it works as expected

**Suggested solution:**
It seems to me that the script doesn't load babel.config.js babel configurations, and just expects a .babelrc in a parent directory. Adding the plugin as suggested by the aforementioned error in the babel.config has no effects indeed

**Comment by akameco** [comment]
Fixed by https://github.com/akameco/read-babelrc-up/pull/6
