### ISSUE TITLE
Append new translations to extracted json

### ISSUE THREAD

**Issue by VanDavv** [akameco/extract-react-intl-messages#5]
Hi!
First, thank you for your great work with this plugin!

However, I extracted messages to json file (worked as expected), then I introduced new messages and tried to extract messages again.

Expected:
- new messages are appended to json file, keeping already present content untouched

Observed:
- content is untouched (as expected) but new messages are not appended to json document (not as expected)

Steps to reproduce:
- extract messages (default language en, other languages: de)
- add new messages
- add any translations to de.json file
- extract messages again
- check content of both en.json and de.json

**Comment by akameco** [comment]
Thank you for your issue @VanDavv :)

Well, it does not reproduce in my environment.
Could you show me the repository?

**Comment by VanDavv** [comment]
It came out that I had an issue with the translations itself, so extract script couldn't see them :) when i fixed it, everything worked as expected :) thanks!
