### ISSUE TITLE
Restore the `module-name` option

### ISSUE THREAD

**Issue by rapka** [akameco/extract-react-intl-messages#52]
**Do you want to request a *feature* or report a *bug*?:**
Feature

**What is the current/expected behavior?:**
What was the reason that the `module-name` option was removed in 2.0.0? I'd like to upgrade to version 2, but my use case requires that functionality. 

**Suggested solution:**
Looking at the commit that removed it, it doesn't seem like the functionality would be too hard to restore, but I'm not sue if there was an underlying reason that necessitated its deletion.

**Comment by akameco** [comment]
Use `moduleSourceName` options. Behave the same.
See https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl#options
