### ISSUE TITLE
How to avoid duplicate keys

### ISSUE THREAD

**Issue by lexax666666** [akameco/extract-react-intl-messages#56]
If I have defineMessages in different files with the same ids, extract-react-intl-messages simply overwrites them. How to make it throw an error

**Comment by lexax666666** [comment]
@akameco I looked into the code. It seems if there is duplicate ids in defineMessages, the extraction process will simply overwrite one over the other. For example: 
if I have a file called componentA.jsx, and do
```
const messages = defineMessages({
    first: {
        id: "studio.errorHandlerClient.errorCode",
        defaultMessage: "first"
    }
});
```
and another file called componentB.jsx, and do
```
const messages = defineMessages({
    second: {
        id: "studio.errorHandlerClient.errorCode",
        defaultMessage: "second"
    }
});
```
 After extraction the output file won't contain both messages, only one of them. Is there a setting I can pass in so the output file will contain both messages, mapped to the same id, or throw an warning or error when there are duplicate ids?

**Comment by lexax666666** [comment]
@akameco Is this possible for the cli tool to output multiple files one per component, instead of one file?

**Comment by akameco** [comment]
No, there is no such function.
We recommend using https://github.com/akameco/babel-plugin-react-intl-auto.
