### ISSUE TITLE
babel-plugin-react-intl has been initialised using an options object that does not match the API schema

### ISSUE THREAD

**Issue by patspam** [akameco/extract-react-intl-messages#57]
- version:
- `node` version:
- `npm` (or `yarn`) version: 1.19.0

**Do you want to request a *feature* or report a *bug*?:**
Bug

**What is the current behavior?:**
```
./node_modules/extract-react-intl-messages/cli.js -o src/i18n/messages -l=en,fr,de -d en --flat false 'src/**/*.js'
ValidationError: [BABEL] /path/to/foo.js: Invalid options object. babel-plugin-react-intl has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'f'. These properties are valid:
   object { moduleSourceName?, enforceDefaultMessage?, enforceDescriptions?, extractSourceLocation?, messagesDir?, overrideIdFn?, removeDefaultMessage?, extractFromFormatMessageCall?, additionalComponentNames
? } (While processing: "base$0$0")
    at Object.validate [as default] (/path/to/node_modules/babel-plugin-react-intl/node_modules/schema-utils/dist/validate.js:50:11)
```

**What is the expected behavior?:**

**Suggested solution:**

**Comment by janitza-trhi** [comment]
Same here. Mabe it has something to do with die cli parser, since property "f" may come from option "format "https://github.com/akameco/extract-react-intl-messages/blob/master/cli.js#L39
It happend without changing any package.json.

**Comment by Lpaydat** [comment]
Facing the same issue.
Have any update/solution here?

**Comment by Lpaydat** [comment]
P.S. This issue does not appear on version 2.2.1, may be it is related with the issue mentioned at #55 ?

**Comment by BerndWessels** [comment]
Same here
`"extract-react-intl-messages": "^2.3.3",`

**Comment by n-sviridenko** [comment]
Same here

**Comment by akameco** [comment]
Fixed. Try update to the latest version 🚀
