### ISSUE TITLE
extractReactIntl named export is overwritten

### ISSUE THREAD

**Issue by gautier-lefebvre** [akameco/extract-react-intl-messages#58]
- version: 2.3.3
- `node` version: 10.16.0
- `npm` (or `yarn`) version: yarn 1.19.1

**Do you want to request a *feature* or report a *bug*?:**
Report a bug

**What is the current behavior?:**

```js
const { extractReactIntl } = require('extract-react-intl-messages');
// extractReactIntl is undefined
```

**What is the expected behavior?:**
The symbol is exported from the module, so I want to be able to import it.

**Suggested solution:**

In `index.ts`, at line 67, you do

```js
export const extractReactIntl = _extractReactIntl
```

But at line 138 you write this

```js
module.exports = extractMessage
```

For CommonJS, line 67 is transpiled to `exports.extractReactIntl = _extractReactIntl`, so at line 138 you overwrite completely `exports`.

Easiest fix, since you want to be able to use require without `.default`, would be simply to assign `extractReactIntl` as a property of `extractMessage`:

```js
extractMessage.extractReactIntl = _extractReactIntl

export default extractMessage

// For CommonJS default export support
module.exports = extractMessage
module.exports.default = extractMessage
```

This way you don't change your API (but on the other hand you always get `extractReactIntl` when you `import default`, which is not problematic given that this module is not meant to be used in a tree-shaking context).

**Comment by akameco** [comment]
@gautier-lefebvre Thank you 👍
