### ISSUE TITLE
How to use extract-react-intl-messages in react-native project ?

### ISSUE THREAD

**Issue by functionwell** [akameco/extract-react-intl-messages#59]
- version: 2.3.3
- `node` version: 10.17.0
- `npm` (or `yarn`) version: npm 6.11.3

**Do you want to request a *feature* or report a *bug*?:**
bug

**What is the current behavior?:**
When use with react-native project, end with this error :

ValidationError: [BABEL]: Invalid options object. babel-plugin-react-intl has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'f'. These properties are valid:
   object { moduleSourceName?, enforceDefaultMessage?, enforceDescriptions?, extractSourceLocation?, messagesDir?, overrideIdFn?, removeDefaultMessage?, extractFromFormatMessageCall?, additionalComponentNames? } (While processing: "base$0$0")

babel.config.js is like this:
`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};`

**What is the expected behavior?:**
extract messages work well with `react-native init` apps

**Suggested solution:**

**Comment by akameco** [comment]
Fixed. Try update to the latest version 🚀
