### ISSUE TITLE
Turn off values overwritting

### ISSUE THREAD

**Issue by VanDavv** [akameco/extract-react-intl-messages#6]
Hi

By default, when I want to extract translations (e.x. to `en.json` file) and this file is already present, this plugin overrides previously present translations. Is there a way to turn off overwritting?

**Example**
I have a file `messages.js` with
```
export default defineMessages({
    foo: 'bar'
})
```
Then, i extract this to `en.json`:
```
{
    "foo": "bar"
}
```
But, my translator changes this line
```
{
   "foo": "anotherBar"
}
```
Then, when i run extraction again i would expect this line to stay the same, but instead i recieve
```
{
    "foo": "bar"
}
```

**Comment by akameco** [comment]
@VanDavv Thank you for your reporting :)

Not currently support it.
Welcome PR if you want it 👍
