### ISSUE TITLE
Empty translation files if project uses babel.config.js instead of .babelrc

### ISSUE THREAD

**Issue by Evanion** [akameco/extract-react-intl-messages#71]
- version: 4.1.1
- `node` version: 12.11.1
- `yarn` version: 1.22.4

I have used this tool about a year ago (#35 ), in a react-native project, And it worked fine, now, with the same setup, on a newly generated project I'm only getting empty files.

_package.json_
```
{
"scripts": {
    ...
    "i18n:extract": "extract-messages -l=en,sv -o src/Locales -d en --flat true 'src/**/!(*.test).ts'",
  },
  "dependencies": {
    ...
    "@formatjs/intl-relativetimeformat": "^4.5.9",
    "intl": "^1.2.5",
    "intl-pluralrules": "^1.1.1",
    "react": "16.13.1",
    "react-intl": "^4.3.1",
    "react-native": "0.62.1",
    ...
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.0",
    "@babel/preset-typescript": "^7.9.0",
    "@babel/runtime": "^7.8.4",
    "babel-plugin-react-intl": "^7.1.0",
    "extract-react-intl-messages": "^4.1.1",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-intl-translations-manager": "^5.0.3",
    ...
  },
}
```

_babel.config.js_
```
module.exports = {
  presets: [
    '@babel/preset-typescript',
    'module:metro-react-native-babel-preset',
  ],
};
```
_src/Screens/Profile/Profile.messages.ts_
```
import {defineMessages} from 'react-intl';

export const messages = defineMessages({
  ...
  fieldPersonalNumber: {
    id: 'profile.field.personalNumber',
    defaultMessage: 'Personal number',
    description: 'Field label for the personal number field',
  },
});

```

**What is the current behavior?:**
If you generate a new react-native project, the babel config is handled in an `babel.config.js` file. The result is empty translation files 

_src/Locales/en.json_
```
{}
```
**What is the expected behavior?:**
That the default translation file contains the keys and default message.
_src/Locales/en.json_
```
{
  "profile.field.personalNumber": "Personal number"
}
```

**Workaround:**
Duplicate your `babel.config.js`  to a `.babelrc` in your project (React-native requires `babel.config.js`).

**Suggested solution:**
Add support for `babel.config.js` files.
add a notice in the readme that this tool requires `@babel/preset-typescript` as a preset in your babel config.

**Comment by ysgk** [comment]
I'm facing the issue, too. 
FYI, It can be reproduced by just converting .babelrc into .babelrc.js in the [sample project of babel-plugin-react-intl-auto](https://github.com/akameco/babel-plugin-react-intl-auto/tree/master/examples/with-typescript). Running `yarn i18n` outputs empty translations.

Lastly, thanks for your awesome libraries, @akameco.

**Comment by akameco** [comment]
I created a sample project. Please try to reference.

- sample: https://github.com/akameco/extract-react-intl-messages/tree/master/example/with-typescript
- readme: https://github.com/akameco/extract-react-intl-messages#typescript

It works when written as follows.

`babel.config.js`

```js
module.exports = function (api) {
  api.cache(true)

  return {
    presets: ['@babel/preset-react', '@babel/preset-typescript']
  }
}
```

**Comment by gertsonderby** [comment]
I'm having this issue via the API, where having no `.babelrc` causes empty translation files, having no babel.config.js causes it to error out because the code is not transpiled, and having both(!) works. I would dearly love to be able to feed a babel config to the API call as an option.

**Comment by ysgk** [comment]
I didn't know that .js format has some [cache related issue](https://babeljs.io/docs/en/config-files#supported-file-extensions). I'll rename my config to .json. Thanks.

**Comment by gertsonderby** [comment]
I take it I should open a separate issue for my API-based troubles.
