### ISSUE TITLE
Tool does not export messages defined with intl.formatMessage

### ISSUE THREAD

**Issue by zcapin** [akameco/extract-react-intl-messages#77]
- version:
- `node` version: v10.16.3
- `npm` (or `yarn`) version: 6.9.0

**Do you want to request a *feature* or report a *bug*?:**
I want to report 'bug'? Not sure if its a bug, maybe just delete from README.md or i missed something
**What is the current behavior?:**
After i used the command, messages defined with intl.formatMessage are not exported
NODE_ENV=development extract-messages -l=en,ja -o src/translations -d en --flat false \"./src/**/*.tsx\"
**What is the expected behavior?:**
Like in the README.md it should export the messages.
**Suggested solution:**
If you dont have this feature, remove it from README.md or suggest a flag on how to use it.

**Comment by zcapin** [comment]
For those who had the same problem as me, issue can be resolved with extra config in babelrc file, more info on: https://formatjs.io/docs/tooling/babel-plugin#via-node-api. Cheers!

{
  "presets": ["react-app"],
  "plugins": [
    [
      "react-intl",
      {
        "messagesDir": "./build/messages",
        "extractSourceLocation": true,
        "extractFromFormatMessageCall": true
      }
    ]
  ]
}

**Comment by iwan-uschka** [comment]
@akameco what do you think about adding a little info to the docs about this issue? Don't know if this is a `extract-react-intl-messages` related issue. Thx and cheers.
