### ISSUE TITLE
What is the purpose of the `--default-locale` option?

### ISSUE THREAD

**Issue by serhiipalash** [akameco/extract-react-intl-messages#9]
What is the purpose of the `--default-locale` option?

Explain it please.

**Comment by akameco** [comment]
@serhiipalash

English is not the first language in some cases. For example, Japanese often sets Japanese as the default language. Setting the default language will extract the message from the component.

```js
export default defineMessages({
  hello: {
    id: 'a.hello',
    defaultMessage: 'こんにちは'
  },
})
```

```
$ extract-messages -l=en,ja -o i18n -d ja '**/*.js'
```

ja.json

```json
{
  "a.hello": "こんにちは"
}
```

en.json

```json
{
  "a.hello": "",
}
```

**Comment by serhiipalash** [comment]
Ah, really! Sorry, for misunderstanding. 
I use `babel-plugin-react-intl-auto` and I have everywhere just `message: 'Name'`, not `defaultMessage: 'Name'`.
Thansk!
